name: internship_task_studyoio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  get: ^4.6.5
  intl: ^0.18.1
  date_picker_timeline: ^1.2.5
  animated_text_kit: ^4.2.2
  sliding_up_panel: ^2.0.0+1
  horizontal_week_calendar: ^0.0.11
  http: ^0.13.5
  shared_preferences: ^2.0.20
  firebase_core: ^2.24.0
  firebase_auth: ^4.14.0
  firebase_storage: ^11.5.1
  cloud_firestore: ^4.13.2
  awesome_notifications: ^0.8.2
  firebase_database: ^10.3.6
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
